services:
    RequestObjectResolverBundle\Resolver\RequestHeadersResolver:
        arguments:
            - '@validator'
        tags:
            - { name: 'controller.argument_value_resolver', priority: 50 }

    RequestObjectResolverBundle\Resolver\RequestCookiesResolver:
        tags:
            - { name: 'controller.argument_value_resolver', priority: 50 }

    RequestObjectResolverBundle\Resolver\RequestObjectResolver:
        arguments:
            - '@serializer'
            - '@validator'
            - '@event_dispatcher'
        tags:
            - { name: 'controller.argument_value_resolver', priority: 50 }
