services:
    _defaults:
        autowire: true

    RequestObjectResolverBundle\Resolver\RequestHeadersResolver:
        tags:
            - { name: 'controller.argument_value_resolver', priority: 50 }

    RequestObjectResolverBundle\Resolver\RequestCookiesResolver:
        tags:
            - { name: 'controller.argument_value_resolver', priority: 50 }

    RequestObjectResolverBundle\Resolver\RequestObjectResolver:
        tags:
            - { name: 'controller.argument_value_resolver', priority: 50 }
