name: Prefer lower dependencies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bundle-tests:
    runs-on: ubuntu-latest
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - uses: actions/checkout@v2
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: composer update --no-ansi --no-interaction --no-scripts --no-progress --prefer-lowest
    - name: Execute phpstan checks
      run: vendor/bin/phpstan --memory-limit=-1 --no-progress
    - name: Execute ecs checks
      run: vendor/bin/ecs --no-error-table --no-progress-bar
    - name: PHPUnit Tests
      uses: php-actions/phpunit@v3
      env:
        XDEBUG_MODE: coverage
      with:
        bootstrap: vendor/autoload.php
        configuration: phpunit.xml.dist
        php_extensions: xdebug
        coverage_clover: coverage/clover.xml
    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.xml
        verbose: true
